[package]
name = "http_api_derive"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.10"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
