[package]
name = "api-builder"
version = "0.1.0"
authors = ["Aleksey Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
actix-web = "0.6.10"
exonum = "0.7.1"
failure = "0.1.1"
futures = "0.1.0"
serde = "1.0.63"
serde_derive = "1.0.63"
serde_json = "1.0.18"
serde_urlencoded = "0.5.2"